[profile.default]
src = "src"
out = "out"
libs = ["lib"]
remappings=["@chainlink/contracts/=lib/chainlink-brownie-contracts/contracts/"]
ffi=true#used to run foundary commands on our pc

# See more config options https://github.com/foundry-rs/foundry/tree/master/config
